import { Menu } from "@/types";

// This file is auto-generated. Do not edit directly.
// @see https://raw.githubusercontent.com/ryohidaka/saizeriya-menus/main/saizeriya.json
export const MENUS: Menu[] = [
  {
    id: 1202,
    name: "小エビのサラダ",
    nameEn: "Shrimp Salad",
    nameZh: "小甜虾沙拉",
    price: 319,
    priceWithTax: 350,
    calorie: 192,
    salt: 1.5,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "サラダ",
    isAlcohol: false,
    icon: "🍤",
    preId: "SA02",
    isEast: true,
    isWest: true,
  },
  {
    id: 1205,
    name: "わかめのサラダ",
    nameEn: "Seaweed Salad",
    nameZh: "海藻沙拉",
    price: 319,
    priceWithTax: 350,
    calorie: 174,
    salt: 2.9,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "サラダ",
    isAlcohol: false,
    icon: "🥗",
    preId: "SA05",
    isEast: true,
    isWest: true,
  },
  {
    id: 1207,
    name: "モッツァレラのサラダ",
    nameEn: "Green Salad with Buffalo Mozzarella Cheese",
    nameZh: "水牛马苏里拉芝士蔬菜沙拉",
    price: 364,
    priceWithTax: 400,
    calorie: 243,
    salt: 0.6,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "サラダ",
    isAlcohol: false,
    icon: "🥗",
    preId: "SA07",
    isEast: false,
    isWest: false,
  },
  {
    id: 1208,
    name: "グリーンサラダ",
    nameEn: "Green Salad",
    nameZh: "绿色的沙拉",
    price: 319,
    priceWithTax: 350,
    calorie: 166,
    salt: 0.7,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "サラダ",
    isAlcohol: false,
    icon: "🥗",
    preId: "SA08",
    isEast: false,
    isWest: false,
  },
  {
    id: 1209,
    name: "チキンのサラダ",
    nameEn: "Chicken Salad",
    nameZh: "鸡肉沙拉",
    price: 319,
    priceWithTax: 350,
    calorie: 224,
    salt: 1.3,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "サラダ",
    isAlcohol: false,
    icon: "🥗",
    preId: "SA03",
    isEast: true,
    isWest: true,
  },
  {
    id: 1301,
    name: "コーンクリームスープ",
    nameEn: "Creamy Corn Soup",
    nameZh: "奶油玉米浓汤",
    price: 137,
    priceWithTax: 150,
    calorie: 154,
    salt: 1,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "スープ",
    isAlcohol: false,
    icon: "🥣",
    preId: "SU01",
    isEast: true,
    isWest: true,
  },
  {
    id: 1305,
    name: "田舎風ミネストローネ",
    nameEn: "Country-style Minestrone",
    nameZh: "田园风蔬菜汤",
    price: 273,
    priceWithTax: 300,
    calorie: 227,
    salt: 3,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "スープ",
    isAlcohol: false,
    icon: "🥣",
    preId: "SU05",
    isEast: true,
    isWest: true,
  },
  {
    id: 1307,
    name: "たまねぎのズッパ",
    nameEn: "Onion soup, Zuppa",
    nameZh: "洋葱面包汤",
    price: 273,
    priceWithTax: 300,
    calorie: 228,
    salt: 2,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "スープ",
    isAlcohol: false,
    icon: "🥣",
    preId: "SU07",
    isEast: true,
    isWest: true,
  },
  {
    id: 1401,
    name: "辛味チキン",
    nameEn: "Spicy Grilled Chicken",
    nameZh: "香辣鸡翅",
    price: 273,
    priceWithTax: 300,
    calorie: 295,
    salt: 1.8,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "前菜・おつまみ",
    isAlcohol: false,
    icon: "🍗",
    preId: "AA01",
    isEast: true,
    isWest: true,
  },
  {
    id: 1402,
    name: "アロスティチーニ（ラムの串焼き）",
    nameEn: "Arrosticini (Lamb skewers)",
    nameZh: "意式羊肉串（烤羊肉串）",
    price: 364,
    priceWithTax: 400,
    calorie: 224,
    salt: 0.6,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "前菜・おつまみ",
    isAlcohol: false,
    icon: "🍢",
    preId: "AA02",
    isEast: true,
    isWest: true,
  },
  {
    id: 1403,
    name: "ほうれん草のソテー",
    nameEn: "Sauteed Spinach（Salt Oil Sauce）",
    nameZh: "炖煮菠菜（盐油酱）",
    price: 182,
    priceWithTax: 200,
    calorie: 223,
    salt: 1.2,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "前菜・おつまみ",
    isAlcohol: false,
    icon: "🥬",
    preId: "AA03",
    isEast: true,
    isWest: true,
  },
  {
    id: 1404,
    name: "ポップコーンシュリンプ",
    nameEn: "Popcorn Shrimp",
    nameZh: "炸小甜虾",
    price: 273,
    priceWithTax: 300,
    calorie: 234,
    salt: 1.2,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "前菜・おつまみ",
    isAlcohol: false,
    icon: "🍤",
    preId: "AA04",
    isEast: true,
    isWest: true,
  },
  {
    id: 1405,
    name: "エスカルゴのオーブン焼き",
    nameEn: "Grilled Escargots",
    nameZh: "蒜香焗蜗牛",
    price: 364,
    priceWithTax: 400,
    calorie: 220,
    salt: 1.3,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "前菜・おつまみ",
    isAlcohol: false,
    icon: "🥘",
    preId: "AA05",
    isEast: true,
    isWest: true,
  },
  {
    id: 1406,
    name: "小エビのカクテル",
    nameEn: 'Shrimp with "SAIZERIYA" Dressing',
    nameZh: "虾佐“SAIZERIYA”酱汁",
    price: 255,
    priceWithTax: 280,
    calorie: 126,
    salt: 2.3,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "前菜・おつまみ",
    isAlcohol: false,
    icon: "🍤",
    preId: "AA06",
    isEast: true,
    isWest: true,
  },
  {
    id: 1407,
    name: "チョリソー（辛味ソーセージ）",
    nameEn: "Grilled Spicy Sausages",
    nameZh: "口利左香肠（辣猪肉香肠）",
    price: 364,
    priceWithTax: 400,
    calorie: 425,
    salt: 2.9,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "前菜・おつまみ",
    isAlcohol: false,
    icon: "🌭",
    preId: "AA07",
    isEast: true,
    isWest: true,
  },
  {
    id: 1408,
    name: "蒸し鶏の香味ソース",
    nameEn: "Chicken with Flavored Vegetable Sauce（Limited to some stores）",
    nameZh: "鸡肉蔬菜酱（限部分店鋪）",
    price: 255,
    priceWithTax: 280,
    calorie: 192,
    salt: 2.4,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "前菜・おつまみ",
    isAlcohol: false,
    icon: "🐔",
    preId: "AA08",
    isEast: true,
    isWest: true,
  },
  {
    id: 1410,
    name: "ムール貝のガーリック焼き",
    nameEn: "Grilled Mussels with Vegetable Salsa",
    nameZh: "蒜香烤蛤蜊",
    price: 364,
    priceWithTax: 400,
    calorie: 170,
    salt: 1.4,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "前菜・おつまみ",
    isAlcohol: false,
    icon: "🦪",
    preId: "AA10",
    isEast: true,
    isWest: true,
  },
  {
    id: 1411,
    name: "アスパラガスの温サラダ",
    nameEn: "Asparagus with  Cheese ",
    nameZh: "芦笋配山核桃奶酪",
    price: 273,
    priceWithTax: 300,
    calorie: 80,
    salt: 0.7,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "前菜・おつまみ",
    isAlcohol: false,
    icon: "🥗",
    preId: "AA09",
    isEast: false,
    isWest: false,
  },
  {
    id: 1413,
    name: "キャロットラペ",
    nameEn: "Refreshing Carrot Salad",
    nameZh: "爽口胡萝卜沙拉",
    price: 182,
    priceWithTax: 200,
    calorie: 93,
    salt: 0.9,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "前菜・おつまみ",
    isAlcohol: false,
    icon: "🥕",
    preId: "AA13",
    isEast: true,
    isWest: true,
  },
  {
    id: 1414,
    name: "モッツァレラトマト",
    nameEn: "Buffalo Mozzarella Cheese &  Tomato",
    nameZh: "布法罗马苏里拉奶酪和番茄",
    price: 391,
    priceWithTax: 430,
    calorie: 255,
    salt: 0.2,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "前菜・おつまみ",
    isAlcohol: false,
    icon: "🍅",
    preId: "AA14",
    isEast: false,
    isWest: false,
  },
  {
    id: 1415,
    name: "カリッとポテト",
    nameEn: "Crispy Potatoes",
    nameZh: "酥烤马铃薯",
    price: 255,
    priceWithTax: 280,
    calorie: 389,
    salt: 2.1,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "前菜・おつまみ",
    isAlcohol: false,
    icon: "🥔",
    preId: "AA15",
    isEast: false,
    isWest: true,
  },
  {
    id: 1416,
    name: "ポテトのグリル",
    nameEn: "Hashed Potato",
    nameZh: "",
    price: 273,
    priceWithTax: 300,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "前菜・おつまみ",
    isAlcohol: false,
    icon: "🥔",
    preId: "",
    isEast: true,
    isWest: false,
  },
  {
    id: 1417,
    name: "バッファローモッツァレラのカプレーゼ",
    nameEn: "Buffalo Mozzarella Cheese &  Tomato",
    nameZh: "",
    price: 391,
    priceWithTax: 430,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "前菜・おつまみ",
    isAlcohol: false,
    icon: "🍅",
    preId: "",
    isEast: true,
    isWest: true,
  },
  {
    id: 1422,
    name: "ハモン・セラーノ",
    nameEn: "Jamon Serrano",
    nameZh: "火腿塞拉诺",
    price: 291,
    priceWithTax: 320,
    calorie: 39,
    salt: 0.9,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "前菜・おつまみ",
    isAlcohol: false,
    icon: "🍖",
    preId: "AA22",
    isEast: true,
    isWest: true,
  },
  {
    id: 1423,
    name: "生ハムとバッファローモッツァレラの盛合せ",
    nameEn: "Jamon Serrano &  Buffalo Mozzarella Cheese",
    nameZh: "火腿塞拉诺和水牛马苏里拉奶酪",
    price: 455,
    priceWithTax: 500,
    calorie: 146,
    salt: 1,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "前菜・おつまみ",
    isAlcohol: false,
    icon: "🧀",
    preId: "",
    isEast: true,
    isWest: true,
  },
  {
    id: 1425,
    name: "柔らか青豆の温サラダ",
    nameEn: "Green Peas with  Cheese & Egg",
    nameZh: "鲜嫩青豆加佩科里诺干酪温色拉",
    price: 182,
    priceWithTax: 200,
    calorie: 216,
    salt: 1.4,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "前菜・おつまみ",
    isAlcohol: false,
    icon: "🫛",
    preId: "AA06",
    isEast: true,
    isWest: true,
  },
  {
    id: 1435,
    name: "スイートコーン",
    nameEn: "Sweet Corn",
    nameZh: "",
    price: 182,
    priceWithTax: 200,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "前菜・おつまみ",
    isAlcohol: false,
    icon: "🥗",
    preId: "",
    isEast: true,
    isWest: true,
  },
  {
    id: 1452,
    name: "アロスティチーニ（ラムの串焼き）(Wサイズ)",
    nameEn: "Arrosticini (Lamb skewers)",
    nameZh: "意式羊肉串（烤羊肉串）",
    price: 728,
    priceWithTax: 800,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "前菜・おつまみ",
    isAlcohol: false,
    icon: "🍢",
    preId: "AA52",
    isEast: true,
    isWest: true,
  },
  {
    id: 2101,
    name: "ミラノ風ドリア",
    nameEn: "Meat Sauce Doria",
    nameZh: "米兰风肉酱多利亚饭",
    price: 273,
    priceWithTax: 300,
    calorie: 521,
    salt: 2.5,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ドリア&グラタン",
    isAlcohol: false,
    icon: "🥘",
    preId: "DG01",
    isEast: true,
    isWest: true,
  },
  {
    id: 2103,
    name: "半熟卵のミラノ風ドリア",
    nameEn: "Meat Sauce & Coddled Egg Doria",
    nameZh: "半熟蛋配米兰风多利亚肉酱饭",
    price: 319,
    priceWithTax: 350,
    calorie: 604,
    salt: 2.7,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ドリア&グラタン",
    isAlcohol: false,
    icon: "🥘",
    preId: "DG03",
    isEast: true,
    isWest: true,
  },
  {
    id: 2106,
    name: "タラコとエビのドリア",
    nameEn: "Doria with “TARAKO”Sauce & Shrimp",
    nameZh: "鳕鱼籽虾焗饭",
    price: 364,
    priceWithTax: 400,
    calorie: 578,
    salt: 2.8,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ドリア&グラタン",
    isAlcohol: false,
    icon: "🥘",
    preId: "DG06",
    isEast: false,
    isWest: true,
  },
  {
    id: 2108,
    name: "焼チーズ ミラノ風ドリア",
    nameEn: "Doria with Meat Sauce & Cheese",
    nameZh: "多利亚肉酱和奶酪",
    price: 319,
    priceWithTax: 350,
    calorie: 652,
    salt: 2.9,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ドリア&グラタン",
    isAlcohol: false,
    icon: "🥘",
    preId: "DG08",
    isEast: true,
    isWest: true,
  },
  {
    id: 2109,
    name: "エビとタラコのクリームグラタン（全粒粉）",
    nameEn: "Gratin with “TARAKO”Sauce & Shrimp",
    nameZh: "TARAKO醬蝦焗烤",
    price: 391,
    priceWithTax: 400,
    calorie: 481,
    salt: 2.1,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ドリア&グラタン",
    isAlcohol: false,
    icon: "🥘",
    preId: "",
    isEast: false,
    isWest: true,
  },
  {
    id: 2110,
    name: "タラコとポップコーンシュリンプのドリア",
    nameEn: "",
    nameZh: "",
    price: 364,
    priceWithTax: 400,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ドリア&グラタン",
    isAlcohol: false,
    icon: "🥘",
    preId: "",
    isEast: true,
    isWest: false,
  },
  {
    id: 2115,
    name: "ポップコーンシュリンプとタラコのクリームグラタン（全粒粉）",
    nameEn: "",
    nameZh: "",
    price: 391,
    priceWithTax: 430,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ドリア&グラタン",
    isAlcohol: false,
    icon: "🥘",
    preId: "",
    isEast: true,
    isWest: false,
  },
  {
    id: 2203,
    name: "バッファローモッツァレラのマルゲリータピザ",
    nameEn: "Pizza with  Buffalo Mozzarella Cheese",
    nameZh: "水牛马苏里拉披萨",
    price: 364,
    priceWithTax: 400,
    calorie: 544,
    salt: 2.4,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ピザ",
    isAlcohol: false,
    icon: "🍕",
    preId: "PZ02",
    isEast: true,
    isWest: true,
  },
  {
    id: 2204,
    name: "野菜ときのこのピザ",
    nameEn: "Pizza with Mushrooms & Vegetable Salsa",
    nameZh: "蔬菜蘑菇比萨",
    price: 364,
    priceWithTax: 400,
    calorie: 593,
    salt: 3.2,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ピザ",
    isAlcohol: false,
    icon: "🍕",
    preId: "PZ04",
    isEast: true,
    isWest: true,
  },
  {
    id: 2206,
    name: "たっぷりコーンのピザ",
    nameEn: "Corn Pizza",
    nameZh: "足量甜玉米比萨",
    price: 364,
    priceWithTax: 400,
    calorie: 624,
    salt: 2.6,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ピザ",
    isAlcohol: false,
    icon: "🍕",
    preId: "PZ06",
    isEast: true,
    isWest: true,
  },
  {
    id: 2208,
    name: "ソーセージピザ",
    nameEn: "Sausage Pizza",
    nameZh: "香肠比萨",
    price: 364,
    priceWithTax: 400,
    calorie: 710,
    salt: 4.1,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ピザ",
    isAlcohol: false,
    icon: "🍕",
    preId: "PZ08",
    isEast: true,
    isWest: true,
  },
  {
    id: 2301,
    name: "タラコソースシシリー風",
    nameEn: "",
    nameZh: "",
    price: 364,
    priceWithTax: 400,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "パスタ",
    isAlcohol: false,
    icon: "🍝",
    preId: "",
    isEast: true,
    isWest: true,
  },
  {
    id: 2303,
    name: "ペペロンチーノ",
    nameEn: "Spaghetti Peperoncino",
    nameZh: "香辣意面",
    price: 273,
    priceWithTax: 300,
    calorie: 582,
    salt: 1.9,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "パスタ",
    isAlcohol: false,
    icon: "🍝",
    preId: "PA03",
    isEast: true,
    isWest: true,
  },
  {
    id: 2304,
    name: "パルマ風スパゲティ",
    nameEn: "Spaghetti with tomato＆pancetta",
    nameZh: "番茄培根意大利面",
    price: 364,
    priceWithTax: 400,
    calorie: 753,
    salt: 3.1,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "パスタ",
    isAlcohol: false,
    icon: "🍝",
    preId: "PA04",
    isEast: true,
    isWest: true,
  },
  {
    id: 2305,
    name: "カルボナーラ",
    nameEn: "Spaghetti Carbonara",
    nameZh: "奶油培根意面",
    price: 455,
    priceWithTax: 500,
    calorie: 799,
    salt: 3.1,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "パスタ",
    isAlcohol: false,
    icon: "🍝",
    preId: "PA05",
    isEast: true,
    isWest: true,
  },
  {
    id: 2306,
    name: "ミートソースボロニア風",
    nameEn: "Spaghetti Meat Sauce",
    nameZh: "意大利肉酱面",
    price: 364,
    priceWithTax: 400,
    calorie: 604,
    salt: 3.6,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "パスタ",
    isAlcohol: false,
    icon: "🍝",
    preId: "PA02",
    isEast: true,
    isWest: true,
  },
  {
    id: 2310,
    name: "スープ入り塩味ボンゴレ",
    nameEn: 'Spaghetti"VONGOLE"',
    nameZh: "意大利面“VONGOLE”",
    price: 455,
    priceWithTax: 500,
    calorie: 872,
    salt: 2.5,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "パスタ",
    isAlcohol: false,
    icon: "🍝",
    preId: "PA10",
    isEast: true,
    isWest: true,
  },
  {
    id: 2316,
    name: "半熟卵のミートソースボロニア風",
    nameEn: "Spaghetti Meat Sauce with Coddled Egg",
    nameZh: "半熟蛋配意大利肉酱面",
    price: 410,
    priceWithTax: 450,
    calorie: 673,
    salt: 3.8,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "パスタ",
    isAlcohol: false,
    icon: "🍝",
    preId: "PA12",
    isEast: true,
    isWest: true,
  },
  {
    id: 2317,
    name: "半熟卵のぺペロンチーノ",
    nameEn: "Spaghetti Peperoncino with soft-boiled egg",
    nameZh: "半熟蛋配香辣意面",
    price: 319,
    priceWithTax: 350,
    calorie: 665,
    salt: 2.1,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "パスタ",
    isAlcohol: false,
    icon: "🍝",
    preId: "PA17",
    isEast: true,
    isWest: true,
  },
  {
    id: 2320,
    name: "小エビのタラコソース",
    nameEn: "Spaghetti “TARAKO” Sauce with Shrimp",
    nameZh: "意大利面“TARAKO”虾酱",
    price: 491,
    priceWithTax: 540,
    calorie: 594,
    salt: 2.8,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "パスタ",
    isAlcohol: false,
    icon: "🍝",
    preId: "PA20",
    isEast: true,
    isWest: true,
  },
  {
    id: 2321,
    name: "きのことほうれん草のクリームスパゲッティ",
    nameEn: "Spaghetti with spinach and mushroom cream",
    nameZh: "菠菜蘑菇奶油意大利面",
    price: 546,
    priceWithTax: 600,
    calorie: 856,
    salt: 3.7,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "パスタ",
    isAlcohol: false,
    icon: "🍝",
    preId: "",
    isEast: true,
    isWest: true,
  },
  {
    id: 2325,
    name: "ペンネアラビアータ（全粒粉）",
    nameEn: "Whole wheat penne arrabbiata",
    nameZh: "全麥通心粉",
    price: 391,
    priceWithTax: 400,
    calorie: 444,
    salt: 2.8,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "パスタ",
    isAlcohol: false,
    icon: "🍝",
    preId: "PA25",
    isEast: true,
    isWest: true,
  },
  {
    id: 2328,
    name: "イカの墨入りセピアソース",
    nameEn: "Spaghetti al Nero di Seppia",
    nameZh: "墨鱼汁海鲜意面",
    price: 455,
    priceWithTax: 500,
    calorie: 603,
    salt: 1.8,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "パスタ",
    isAlcohol: false,
    icon: "🍝",
    preId: "",
    isEast: true,
    isWest: true,
  },
  {
    id: 2402,
    name: "若鶏のディアボラ風",
    nameEn: "Grilled Chicken with Chopped Vegetable Sauce",
    nameZh: "意式恶魔风嫩鸡排",
    price: 455,
    priceWithTax: 500,
    calorie: 673,
    salt: 2.8,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ハンバーグ",
    isAlcohol: false,
    icon: "🐔",
    preId: "MT02",
    isEast: true,
    isWest: true,
  },
  {
    id: 2403,
    name: "イタリアンハンバーグ",
    nameEn: "Italian Hamburg Steak",
    nameZh: "意大利风味汉堡牛排",
    price: 455,
    priceWithTax: 500,
    calorie: 670,
    salt: 3,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ハンバーグ",
    isAlcohol: false,
    icon: "🍖",
    preId: "MT03",
    isEast: true,
    isWest: true,
  },
  {
    id: 2404,
    name: "柔らかチキンのチーズ焼き",
    nameEn: "Grilled Chicken with Cheese",
    nameZh: "意大利风芝士鸡排",
    price: 455,
    priceWithTax: 500,
    calorie: 725,
    salt: 2.8,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ハンバーグ",
    isAlcohol: false,
    icon: "🐔",
    preId: "MT04",
    isEast: true,
    isWest: true,
  },
  {
    id: 2406,
    name: "ハンバーグステーキ",
    nameEn: "Hamburg Steak(Demi-Glace Sauce)",
    nameZh: "汉堡牛排(半冰酱)",
    price: 364,
    priceWithTax: 400,
    calorie: 571,
    salt: 2.5,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ハンバーグ",
    isAlcohol: false,
    icon: "🍖",
    preId: "MT01",
    isEast: true,
    isWest: true,
  },
  {
    id: 2407,
    name: "ディアボラ風ハンバーグ",
    nameEn: "Hamburg Steak with Chopped Vegetable Sauce",
    nameZh: "意式恶魔风汉堡牛排",
    price: 455,
    priceWithTax: 500,
    calorie: 618,
    salt: 3.1,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ハンバーグ",
    isAlcohol: false,
    icon: "🍖",
    preId: "MT07",
    isEast: true,
    isWest: true,
  },
  {
    id: 2413,
    name: "ラム（仔羊）と野菜のグリル",
    nameEn: "Grilled Lamb ＆ Vegetables",
    nameZh: "烤羊肉＆蔬菜",
    price: 791,
    priceWithTax: 870,
    calorie: 371,
    salt: 2.4,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ハンバーグ",
    isAlcohol: false,
    icon: "🍖",
    preId: "MT13",
    isEast: true,
    isWest: true,
  },
  {
    id: 2418,
    name: "ミックスグリル",
    nameEn: "Mixed Grill",
    nameZh: "混合烧烤",
    price: 591,
    priceWithTax: 650,
    calorie: 779,
    salt: 3.6,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ハンバーグ",
    isAlcohol: false,
    icon: "🍖",
    preId: "",
    isEast: true,
    isWest: true,
  },
  {
    id: 3101,
    name: "ライス",
    nameEn: "Rice",
    nameZh: "米饭",
    price: 137,
    priceWithTax: 150,
    calorie: 303,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ライス・パン",
    isAlcohol: false,
    icon: "🍚",
    preId: "RP01",
    isEast: true,
    isWest: true,
  },
  {
    id: 3102,
    name: "ラージライス",
    nameEn: "Large Rice",
    nameZh: "米饭",
    price: 182,
    priceWithTax: 200,
    calorie: 303,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ライス・パン",
    isAlcohol: false,
    icon: "🍚",
    preId: "RP02",
    isEast: true,
    isWest: true,
  },
  {
    id: 3103,
    name: "スモールライス",
    nameEn: "Small Rice",
    nameZh: "米饭",
    price: 91,
    priceWithTax: 100,
    calorie: 303,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ライス・パン",
    isAlcohol: false,
    icon: "🍚",
    preId: "RP03",
    isEast: true,
    isWest: true,
  },
  {
    id: 3104,
    name: "シナモンプチフォッカ",
    nameEn: "Petit Focaccia with Cinnamon Sugar",
    nameZh: "肉桂糖迷你香草面包",
    price: 182,
    priceWithTax: 200,
    calorie: 246,
    salt: 0.8,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ライス・パン",
    isAlcohol: false,
    icon: "🍞",
    preId: "RP04",
    isEast: false,
    isWest: false,
  },
  {
    id: 3106,
    name: "プチフォッカ",
    nameEn: "Petit Focaccias",
    nameZh: "迷你香草面包",
    price: 137,
    priceWithTax: 150,
    calorie: 214,
    salt: 0.8,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ライス・パン",
    isAlcohol: false,
    icon: "🍞",
    preId: "RP06",
    isEast: false,
    isWest: false,
  },
  {
    id: 3108,
    name: "ミニフィセル",
    nameEn: "Mini Ficelle",
    nameZh: "迷你法式面包",
    price: 137,
    priceWithTax: 150,
    calorie: 189,
    salt: 1,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ライス・パン",
    isAlcohol: false,
    icon: "🥖",
    preId: "RP08",
    isEast: false,
    isWest: false,
  },
  {
    id: 3109,
    name: "ガーリックトースト",
    nameEn: "Garlic Toast",
    nameZh: "蒜香烤面包",
    price: 182,
    priceWithTax: 200,
    calorie: 245,
    salt: 1.1,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ライス・パン",
    isAlcohol: false,
    icon: "🥖",
    preId: "RP09",
    isEast: false,
    isWest: false,
  },
  {
    id: 3110,
    name: "フォッカチオ",
    nameEn: "",
    nameZh: "",
    price: 137,
    priceWithTax: 150,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ライス・パン",
    isAlcohol: false,
    icon: "🍞",
    preId: "",
    isEast: true,
    isWest: true,
  },
  {
    id: 3111,
    name: "ガーリックフォッカチオ",
    nameEn: "",
    nameZh: "",
    price: 182,
    priceWithTax: 200,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ライス・パン",
    isAlcohol: false,
    icon: "🍞",
    preId: "",
    isEast: true,
    isWest: true,
  },
  {
    id: 3112,
    name: "シナモンフォッカチオ",
    nameEn: "",
    nameZh: "",
    price: 182,
    priceWithTax: 200,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ライス・パン",
    isAlcohol: false,
    icon: "🍞",
    preId: "",
    isEast: true,
    isWest: true,
  },
  {
    id: 3201,
    name: "ティラミス　クラシコ",
    nameEn: "Tiramisu",
    nameZh: "提拉米苏经典系列",
    price: 273,
    priceWithTax: 300,
    calorie: 229,
    salt: 0.1,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "デザート (すぐに)",
    isAlcohol: false,
    icon: "🧁",
    preId: "DE01",
    isEast: true,
    isWest: true,
  },
  {
    id: 3204,
    name: "ジェラート＆シナモンプチフォッカ",
    nameEn: "Petit Focaccias with Cinamon Sugar & Italian Gelato",
    nameZh: "肉桂糖迷你香草面包配意大利冰激淋",
    price: 410,
    priceWithTax: 450,
    calorie: 372,
    salt: 0.9,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "デザート (すぐに)",
    isAlcohol: false,
    icon: "🍨",
    preId: "DE04",
    isEast: false,
    isWest: false,
  },
  {
    id: 3205,
    name: "ミルクジェラート",
    nameEn: "Italian Gelato",
    nameZh: "意大利冰激淋",
    price: 228,
    priceWithTax: 250,
    calorie: 121,
    salt: 0.1,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "デザート (すぐに)",
    isAlcohol: false,
    icon: "🍨",
    preId: "DE05",
    isEast: true,
    isWest: true,
  },
  {
    id: 3206,
    name: "イタリアンプリン",
    nameEn: "Italian Cream Caramel",
    nameZh: "意大利布丁",
    price: 228,
    priceWithTax: 250,
    calorie: 216,
    salt: 0.1,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "デザート (すぐに)",
    isAlcohol: false,
    icon: "🍮",
    preId: "DE06",
    isEast: true,
    isWest: true,
  },
  {
    id: 3207,
    name: "チョコレートケーキ",
    nameEn: "Chocolate Cake",
    nameZh: "巧克力蛋糕",
    price: 273,
    priceWithTax: 300,
    calorie: 166,
    salt: 0.1,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "デザート (すぐに)",
    isAlcohol: false,
    icon: "🍰",
    preId: "DE07",
    isEast: true,
    isWest: true,
  },
  {
    id: 3212,
    name: "プリンとティラミス　クラシコの盛合せ",
    nameEn: "Tiramisu & Italian Cream Caramel",
    nameZh: "布丁配提拉米苏",
    price: 455,
    priceWithTax: 500,
    calorie: 445,
    salt: 0.2,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "デザート (すぐに)",
    isAlcohol: false,
    icon: "🍮",
    preId: "DE12",
    isEast: true,
    isWest: true,
  },
  {
    id: 3213,
    name: "トリフアイスクリーム",
    nameEn: "Ice Cream Truffle",
    nameZh: "松露冰激淋",
    price: 319,
    priceWithTax: 350,
    calorie: 164,
    salt: 0.1,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "デザート (すぐに)",
    isAlcohol: false,
    icon: "🍨",
    preId: "DE13",
    isEast: true,
    isWest: true,
  },
  {
    id: 3214,
    name: "ジェラート＆シナモンフォッカチオ",
    nameEn: "",
    nameZh: "",
    price: 410,
    priceWithTax: 450,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "デザート (すぐに)",
    isAlcohol: false,
    icon: "🍨",
    preId: "",
    isEast: true,
    isWest: true,
  },
  {
    id: 3215,
    name: "コーヒーゼリー＆ミルクジェラート",
    nameEn: "Coffee Jelly with Italian Gelato",
    nameZh: "意大利冰激淋配咖啡果冻",
    price: 319,
    priceWithTax: 350,
    calorie: 165,
    salt: 0.1,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "デザート (すぐに)",
    isAlcohol: false,
    icon: "🍨",
    preId: "DE15",
    isEast: true,
    isWest: true,
  },
  {
    id: 3301,
    name: "生ビール キリン一番搾り　ジョッキ",
    nameEn: "",
    nameZh: "",
    price: 364,
    priceWithTax: 400,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ビール・サワー・ノンアルコール",
    isAlcohol: true,
    icon: "🍺",
    preId: "BR01",
    isEast: true,
    isWest: true,
  },
  {
    id: 3302,
    name: "生ビール キリン一番搾り　グラスビール",
    nameEn: "",
    nameZh: "",
    price: 273,
    priceWithTax: 300,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ビール・サワー・ノンアルコール",
    isAlcohol: true,
    icon: "🍺",
    preId: "BR02",
    isEast: true,
    isWest: true,
  },
  {
    id: 3303,
    name: "ノンアルコール アサヒドライゼロ",
    nameEn: "",
    nameZh: "",
    price: 228,
    priceWithTax: 250,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ビール・サワー・ノンアルコール",
    isAlcohol: false,
    icon: "🍺",
    preId: "",
    isEast: true,
    isWest: true,
  },
  {
    id: 3304,
    name: "サワー キリン氷結シチリア産レモン",
    nameEn: "",
    nameZh: "",
    price: 319,
    priceWithTax: 350,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ビール・サワー・ノンアルコール",
    isAlcohol: true,
    icon: "🍺",
    preId: "BR04",
    isEast: true,
    isWest: true,
  },
  {
    id: 3306,
    name: "グラッパ (30ml)",
    nameEn: "",
    nameZh: "",
    price: 273,
    priceWithTax: 300,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ビール・サワー・ノンアルコール",
    isAlcohol: true,
    icon: "🍺",
    preId: "",
    isEast: true,
    isWest: true,
  },
  {
    id: 3401,
    name: "グラスワイン (120ml)　赤",
    nameEn: "",
    nameZh: "",
    price: 91,
    priceWithTax: 100,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ワイン",
    isAlcohol: true,
    icon: "🍷",
    preId: "WN01",
    isEast: true,
    isWest: true,
  },
  {
    id: 3402,
    name: "グラスワイン (120ml)　白",
    nameEn: "",
    nameZh: "",
    price: 91,
    priceWithTax: 100,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ワイン",
    isAlcohol: true,
    icon: "🍷",
    preId: "WN02",
    isEast: true,
    isWest: true,
  },
  {
    id: 3403,
    name: "デカンタ (250ml)　赤",
    nameEn: "",
    nameZh: "",
    price: 182,
    priceWithTax: 200,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ワイン",
    isAlcohol: true,
    icon: "🍷",
    preId: "WN03",
    isEast: true,
    isWest: true,
  },
  {
    id: 3404,
    name: "デカンタ (250ml)　白",
    nameEn: "",
    nameZh: "",
    price: 182,
    priceWithTax: 200,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ワイン",
    isAlcohol: true,
    icon: "🍷",
    preId: "WN04",
    isEast: true,
    isWest: true,
  },
  {
    id: 3405,
    name: "デカンタ (500ml)　赤",
    nameEn: "",
    nameZh: "",
    price: 364,
    priceWithTax: 400,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ワイン",
    isAlcohol: true,
    icon: "🍷",
    preId: "WN05",
    isEast: true,
    isWest: true,
  },
  {
    id: 3406,
    name: "デカンタ (500ml)　白",
    nameEn: "",
    nameZh: "",
    price: 364,
    priceWithTax: 400,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ワイン",
    isAlcohol: true,
    icon: "🍷",
    preId: "WN06",
    isEast: true,
    isWest: true,
  },
  {
    id: 3407,
    name: "マグナム (1500ml)　赤",
    nameEn: "",
    nameZh: "",
    price: 1000,
    priceWithTax: 1100,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ワイン",
    isAlcohol: true,
    icon: "🍾",
    preId: "WN07",
    isEast: true,
    isWest: true,
  },
  {
    id: 3408,
    name: "マグナム (1500ml)　白",
    nameEn: "",
    nameZh: "",
    price: 1000,
    priceWithTax: 1100,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ワイン",
    isAlcohol: true,
    icon: "🍾",
    preId: "WN08",
    isEast: true,
    isWest: true,
  },
  {
    id: 3412,
    name: "ランブルスコロゼ【(ロゼ・発泡)甘口】",
    nameEn: "",
    nameZh: "",
    price: 1000,
    priceWithTax: 1100,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ワイン",
    isAlcohol: true,
    icon: "🍾",
    preId: "WN12",
    isEast: true,
    isWest: true,
  },
  {
    id: 3413,
    name: "ドンラファエロ【(白・発泡)辛口】",
    nameEn: "",
    nameZh: "",
    price: 1000,
    priceWithTax: 1100,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ワイン",
    isAlcohol: true,
    icon: "🍾",
    preId: "WN13",
    isEast: true,
    isWest: true,
  },
  {
    id: 3414,
    name: "ランブルスコセッコ【(赤・発泡)辛口】",
    nameEn: "",
    nameZh: "",
    price: 1000,
    priceWithTax: 1100,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ワイン",
    isAlcohol: true,
    icon: "🍾",
    preId: "WN14",
    isEast: true,
    isWest: true,
  },
  {
    id: 3415,
    name: "ベルデッキオ【(白)辛口】",
    nameEn: "",
    nameZh: "",
    price: 1000,
    priceWithTax: 1100,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ワイン",
    isAlcohol: true,
    icon: "🍾",
    preId: "WN15",
    isEast: true,
    isWest: true,
  },
  {
    id: 3416,
    name: "キャンティ【(赤)辛口】",
    nameEn: "",
    nameZh: "",
    price: 1000,
    priceWithTax: 1100,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ワイン",
    isAlcohol: true,
    icon: "🍾",
    preId: "WN16",
    isEast: true,
    isWest: true,
  },
  {
    id: 3419,
    name: "キャンティ ルフィナ リゼルバ【(赤)辛口】",
    nameEn: "",
    nameZh: "",
    price: 2000,
    priceWithTax: 2200,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ワイン",
    isAlcohol: true,
    icon: "🍾",
    preId: "WN19",
    isEast: true,
    isWest: true,
  },
  {
    id: 3901,
    name: "ティラミス　クラシコ",
    nameEn: "Tiramisu",
    nameZh: "提拉米苏经典系列",
    price: 273,
    priceWithTax: 300,
    calorie: 229,
    salt: 0.1,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "デザート (あとで)",
    isAlcohol: false,
    icon: "🧁",
    preId: "DE01",
    isEast: true,
    isWest: true,
  },
  {
    id: 3904,
    name: "ジェラート＆シナモンプチフォッカ",
    nameEn: "Petit Focaccias with Cinamon Sugar & Italian Gelato",
    nameZh: "肉桂糖迷你香草面包配意大利冰激淋",
    price: 410,
    priceWithTax: 450,
    calorie: 372,
    salt: 0.9,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "デザート (あとで)",
    isAlcohol: false,
    icon: "🍨",
    preId: "DE04",
    isEast: false,
    isWest: false,
  },
  {
    id: 3905,
    name: "ミルクジェラート",
    nameEn: "Italian Gelato",
    nameZh: "意大利冰激淋",
    price: 228,
    priceWithTax: 250,
    calorie: 121,
    salt: 0.1,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "デザート (あとで)",
    isAlcohol: false,
    icon: "🍨",
    preId: "DE05",
    isEast: true,
    isWest: true,
  },
  {
    id: 3906,
    name: "イタリアンプリン",
    nameEn: "Italian Cream Caramel",
    nameZh: "意大利布丁",
    price: 228,
    priceWithTax: 250,
    calorie: 216,
    salt: 0.1,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "デザート (あとで)",
    isAlcohol: false,
    icon: "🍮",
    preId: "DE06",
    isEast: true,
    isWest: true,
  },
  {
    id: 3907,
    name: "チョコレートケーキ",
    nameEn: "Chocolate Cake",
    nameZh: "巧克力蛋糕",
    price: 273,
    priceWithTax: 300,
    calorie: 166,
    salt: 0.1,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "デザート (あとで)",
    isAlcohol: false,
    icon: "🍰",
    preId: "DE07",
    isEast: true,
    isWest: true,
  },
  {
    id: 3912,
    name: "プリンとティラミス　クラシコの盛合せ",
    nameEn: "Tiramisu & Italian Cream Caramel",
    nameZh: "布丁配提拉米苏",
    price: 455,
    priceWithTax: 500,
    calorie: 445,
    salt: 0.2,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "デザート (あとで)",
    isAlcohol: false,
    icon: "🍮",
    preId: "DE12",
    isEast: true,
    isWest: true,
  },
  {
    id: 3913,
    name: "トリフアイスクリーム",
    nameEn: "Ice Cream Truffle",
    nameZh: "松露冰激淋",
    price: 319,
    priceWithTax: 350,
    calorie: 164,
    salt: 0.1,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "デザート (あとで)",
    isAlcohol: false,
    icon: "🍨",
    preId: "DE13",
    isEast: true,
    isWest: true,
  },
  {
    id: 3914,
    name: "ジェラート＆シナモンフォッカチオ",
    nameEn: "",
    nameZh: "",
    price: 410,
    priceWithTax: 450,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "デザート (すぐに)",
    isAlcohol: false,
    icon: "🍨",
    preId: "",
    isEast: true,
    isWest: true,
  },
  {
    id: 3915,
    name: "コーヒーゼリー＆ミルクジェラート",
    nameEn: "Coffee Jelly with Italian Gelato",
    nameZh: "意大利冰激淋配咖啡果冻",
    price: 319,
    priceWithTax: 350,
    calorie: 165,
    salt: 0.1,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "デザート (あとで)",
    isAlcohol: false,
    icon: "🍨",
    preId: "DE15",
    isEast: true,
    isWest: true,
  },
  {
    id: 4301,
    name: "トッピング半熟卵",
    nameEn: "Coddled Egg for Topping",
    nameZh: "加半熟蛋",
    price: 46,
    priceWithTax: 50,
    calorie: 83,
    salt: 0.2,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "トッピング",
    isAlcohol: false,
    icon: "🥚",
    preId: "TP01",
    isEast: true,
    isWest: true,
  },
  {
    id: 4304,
    name: "トッピング野菜ソース",
    nameEn: "Vegetable Paste",
    nameZh: "蔬菜酱",
    price: 91,
    priceWithTax: 100,
    calorie: 72,
    salt: 0.3,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "トッピング",
    isAlcohol: false,
    icon: "🥗",
    preId: "TP04",
    isEast: true,
    isWest: true,
  },
  {
    id: 4307,
    name: "トッピング粉チーズ（グランモラビア）",
    nameEn: "Table Cheese",
    nameZh: "加芝士粉（摩拉維並干酪）",
    price: 91,
    priceWithTax: 100,
    calorie: 91,
    salt: 0.6,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "トッピング",
    isAlcohol: false,
    icon: "🧀",
    preId: "TP07",
    isEast: true,
    isWest: true,
  },
  {
    id: 5101,
    name: "セットドリンクバー",
    nameEn: "Drink Bar (When Ordered with Food)",
    nameZh: "畅饮吧（畅饮吧套餐）",
    price: 182,
    priceWithTax: 200,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ドリンクバー",
    isAlcohol: false,
    icon: "🥤",
    preId: "DB01",
    isEast: true,
    isWest: true,
  },
  {
    id: 5102,
    name: "キッズドリンクバー",
    nameEn: "Drink Bar (Kids)",
    nameZh: "畅饮吧（儿童）",
    price: 91,
    priceWithTax: 100,
    calorie: 0,
    salt: 0,
    category: "キッズ",
    categoryEn: "Kids",
    categoryZh: "孩子们",
    genre: "ドリンクバー",
    isAlcohol: false,
    icon: "🥤",
    preId: "DB02",
    isEast: true,
    isWest: true,
  },
  {
    id: 5103,
    name: "ドリンクバー単品",
    nameEn: "Drink Bar (Only)",
    nameZh: "畅饮吧（單品）",
    price: 273,
    priceWithTax: 300,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ドリンクバー",
    isAlcohol: false,
    icon: "🥤",
    preId: "DB03",
    isEast: true,
    isWest: true,
  },
  {
    id: 5305,
    name: "サイゼリヤ　ドレッシング (500ml)",
    nameEn: "",
    nameZh: "",
    price: 463,
    priceWithTax: 500,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ドレッシング・オリーブオイル",
    isAlcohol: false,
    icon: "🧂",
    preId: "",
    isEast: true,
    isWest: true,
  },
  {
    id: 5306,
    name: "エクストラ・バージン・オリーブオイル (500ml)",
    nameEn: "",
    nameZh: "",
    price: 1112,
    priceWithTax: 1200,
    calorie: 0,
    salt: 0,
    category: "グランド",
    categoryEn: "Grand Menu",
    categoryZh: "主",
    genre: "ドレッシング・オリーブオイル",
    isAlcohol: false,
    icon: "🧂",
    preId: "",
    isEast: true,
    isWest: true,
  },
];
